name    'justinstoller/wix'
version '0.0.1'
source 'git://github.com/justinstoller/puppet-wix.git'
author 'justinstoller'
license 'Apache License, Version 2.0'
summary 'Installs WiX Toolset on Windows'
description 'Installs Wix Toolset (wixtoolset.org) on Windows boxes for creating native wmis.'
project_page 'https://github.com/justinstoller/puppet-wix'
